// eslint-disable-next-line
export default  {
    cart: [],
    buyer: [],
    orders: [],
    products: [
      {
        'id': '1',
        'image':'https://qafacol.vteximg.com.br/arquivos/ids/307891-1500-1500/40230284-60281_1.jpg?v:637124712853830000',
        'name': 'Sport adidas',
        'description': 'Licras 100% elasticas, disponobles en tallas S M L',
        'price': '35.000',
      },
      {
        'id': '2',
        'image':'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQG4sSCpUaFUxOvhhwVFC0seW7j07oNRfhnQ&usqp=CAU',
        'name':'Grand',
        'description':'Licras 100% elasticas, disponobles en tallas S M L ',
        'price':'80.000',
      },
      {
        'id': '3',
        'image':'https://http2.mlstatic.com/licras-nike-deportiva-dama-new-D_NQ_NP_627393-MCO31537143881_072019-Q.jpg',
        'name':'Smokind',
        'description':'Licras 100% elasticas, disponobles en tallas S M L ',
        'price':'75.000',
      },
      {
        'id': '4',
        'image':'https://http2.mlstatic.com/leggins-licra-deportivo-dama-mayoreo-gym-colombiano-rosa-neg-D_Q_NP_755229-MLM32661291161_102019-F.webp',
        'name':'Kinder',
        'description':'Licras 100% elasticas, disponobles en tallas S M L ',
        'price':'18.000',
      },
      {
        'id': '5',
        'image':'http://mlm-s2-p.mlstatic.com/634500-MLM42584315988_072020-O.jpg',
        'name':'Sparta',
        'description':'Licras 100% elasticas, disponobles en tallas S M L ',
        'price':'65.000',
      },
      {
        'id': '6',
        'image':'https://dafitistaticco-a.akamaihd.net/p/patprimo-5502-3555421-1-product.jpg',
        'name': 'Slated',
        'description': 'Licras 100% elasticas, disponobles en tallas S M L',
        'price': '45.000',
      },
    ],
          productsOne: [
        {
          'id': '7',
          'image':'https://i.pinimg.com/originals/f2/4c/ec/f24cecb9f2ac16aaa586d120847912b1.jpg',
          'name':'Blusa Whi I Do',
          'description':'Blusa 100% algodon, disponobles en tallas S M L ',
          'price':'35.000',
        },
        {
          'id': '8',
          'image':'https://i.pinimg.com/originals/f7/da/3d/f7da3d992a84d02ac99015c3a7c1943d.jpg',
          'name':'Addict',
          'description':'Blusa 100% algodon, disponobles en tallas S M L ',
          'price':'35.000',
        },
        {
          'id': '9',
          'image':'https://http2.mlstatic.com/D_NQ_NP_901225-MCO31008799700_062019-W.jpg',
          'name':'Camisilla GYM mujer',
          'description':'Blusa 100% algodon, disponobles en tallas S M L ',
          'price':'60.000',
        },
        {
          'id': '10',
          'image':'https://i.pinimg.com/originals/04/d3/96/04d3966b4566ad426680bd1ac3057a82.jpg',
          'name':'Nirvana GO',
          'description':'Blusa 100% algodon, disponobles en tallas S M L ',
          'price':'47.000',
        },
        {
          'id': '11',
          'image':'https://i.pinimg.com/originals/ea/66/94/ea6694aaf56258f65c46dc7539513a26.jpg',
          'name':'Pin end Fi',
          'description':'Blusa 100% algodon, disponobles en tallas S M L ',
          'price':'25.000',
        },
        {
          'id': '12',
          'image':'https://productos-fel.s3.us-west-2.amazonaws.com/d5f23dca-08c6-4b72-96e3-7a5bb01438a8.jpg',
          'name':'Tirante GYM',
          'description':'Blusa 100% algodon, disponobles en tallas S M L ',
          'price':'50.000',
        },
      ],
      productsJerseys: [
        {
          'id': '13',
          'image':'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKtIUwuQ0PZFVazTZdK6loPQyzo60VooD_zQ&usqp=CAU',
          'name':'Splace',
          'description':'Jerseys 100% Licra, disponobles en tallas S M L ',
          'price':'100.000',
        },
        {
          'id': '14',
          'image':'https://rinatsport.com/media/thumb/1a92d-superior-jersey.png',
          'name':'Spiderman Black',
          'description':'Jerseys 100% Licra, disponobles en tallas S M L ',
          'price':'150.000',
        },
        {
          'id': '15',
          'image':'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHsUrAWJlDbXnMzXjy2tZ-SpZAuJVqr18WaA&usqp=CAU',
          'name':'Wasson',
          'description':'Jerseys 100% Licra, disponobles en tallas S M L ',
          'price':'147.000',
        },
        {
          'id': '16',
          'image':'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqG6LYZhx_k4bAnwUZuhvz4k6cJCycUsQR-A&usqp=CAU',
          'name':'Super Man',
          'description':'Jerseys 100% Licra, disponobles en tallas S M L ',
          'price':'125.000',
        },
        {
          'id': '17',
          'image':'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoLfi18f-HUOfAESdIaNtuLRSkNi5KNXCPtQ&usqp=CAU',
          'name':'Stiderman Red',
          'description':'Jerseys 100% Licra, disponobles en tallas S M LL ',
          'price':'150.000',
        },
        {
          'id': '18',
          'image':'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWERGCAWBC-BiFGqSK3Cyt-aT2S7NJHrpQCw&usqp=CAU',
          'name':'Hitoman Red',
          'description':'Jerseys 100% Licra, disponobles en tallas S M L ',
          'price':'120.000',
        },
      ],
  }